# NumPy & Pandas — Hands-On Lab

Companion notebook for the *NumPy & Pandas* session (Array Operations, DataFrames & Data Manipulation).

**How to use this notebook**
- Run every cell in order (Shift+Enter).
- Each topic has a short **🧪 Try it** cell for you to complete — look for `# TODO`.
- The **✅ Solution** cell right after shows one correct way to do it. Try first, peek second.
- No file uploads needed — we build small sample datasets right here in the notebook.

---

## 0. Setup

In [ ]:
import numpy as np
import pandas as pd

print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)

NumPy version: 2.0.2
Pandas version: 2.2.2


---
# Part 1 — NumPy: Array Operations

## 1.1 Creating arrays

`np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`, `np.random`, `np.eye()`.

In [ ]:
# A 1D array from a list
a1 = np.array([4, 8, 15, 16, 23, 42])
print(a1)

# A 2D array from a nested list
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)

print("zeros:\n", np.zeros((2, 3)))
print("ones:\n", np.ones((2, 3)))
print("arange:", np.arange(0, 10, 2))
print("linspace:", np.linspace(0, 1, 5))
print("identity:\n", np.eye(3))

[ 4  8 15 16 23 42]
[[1 2 3]
 [4 5 6]]
zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]
identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [ ]:
temps=np.array([21,24,19,30])
sevens=np.full((3,3),7)
spaced=np.linspace(0,5,6)
print(temps)
print(sevens)
print(spaced)

[21 24 19 30]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[0. 1. 2. 3. 4. 5.]

### 🧪 Try it
Create:
1. A 1D array `temps` holding the values `[21, 24, 19, 30, 27]`.
2. A 3x3 array of all `7`s using `np.full`.
3. An array of 6 evenly spaced numbers between `0` and `5` using `np.linspace`.

In [ ]:
# TODO: 1. create `temps`
temps = None

# TODO: 2. create a 3x3 array of 7s
sevens = None

# TODO: 3. create 6 evenly spaced numbers between 0 and 5
spaced = None

print(temps)
print(sevens)
print(spaced)

None
None
None

### ✅ Solution

In [ ]:
temps = np.array([21, 24, 19, 30, 27])
sevens = np.full((3, 3), 7)
spaced = np.linspace(0, 5, 6)

print(temps)
print(sevens)
print(spaced)

[21 24 19 30 27]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[0. 1. 2. 3. 4. 5.]

## 1.2 Array attributes

In [ ]:
grid = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("ndim :", grid.ndim) #to find out the dim of array or gird
print("shape:", grid.shape) # to find the dimention of the array
print("size :", grid.size) #to find the number of elements in the array
print("dtype:", grid.dtype) # to find the datatype of element present in the array

ndim : 2
shape: (3, 4)
size : 12
dtype: int64

## 1.3 Indexing & slicing

In [ ]:
m = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print("element [1,2]:", m[1, 2]) #print the 1st row second element as u know the indexing will start from 0
print("first row    :", m[0, :]) # print the first row all elements
print("last column  :", m[:, -1]) #to print last row elements
print("sub-matrix   :\n", m[0:2, 1:3]) #

element [1,2]: 60
first row    : [10 20 30]
last column  : [30 60 90]
sub-matrix   :
 [[20 30]
 [50 60]]

### 🧪 Try it
Using `m` above, get:
1. The middle row (`[40, 50, 60]`).
2. The first two columns of all rows.
3. The bottom-right element using negative indices.

In [ ]:
# TODO 1: middle row
middle_row = None

# TODO 2: first two columns, all rows
first_two_cols = None

# TODO 3: bottom-right element (negative indices)
bottom_right = None

print(middle_row)
print(first_two_cols)
print(bottom_right)

None
None
None

### ✅ Solution

In [ ]:
middle_row = m[1, :]
first_two_cols = m[:, 0:2]
bottom_right = m[-1, -1]

print(middle_row)
print(first_two_cols)
print(bottom_right)

[40 50 60]
[[10 20]
 [40 50]
 [70 80]]
90

## 1.4 Boolean & fancy indexing

In [ ]:
scores = np.array([55, 82, 47, 91, 63, 78, 30])

print("mask        :", scores > 60) #prin the greater side elm as true and lesser elem as false
print("filtered    :", scores[scores > 60]) # print only the elements which are greater than 60
print("fancy index :", scores[[0, 3, 5]]) #print as index wise
print("combined    :", scores[(scores > 50) & (scores < 90)]) # print the scores in bet 50 and 90

mask        : [False  True False  True  True  True False]
filtered    : [82 91 63 78]
fancy index : [55 91 78]
combined    : [55 82 63 78]

### 🧪 Try it
From `scores`, select:
1. All scores that are **failing** (below 50).
2. Scores at positions `1`, `2`, and `4` using fancy indexing.

In [ ]:
# TODO 1: failing scores (< 50)
failing = None

# TODO 2: fancy-index positions 1, 2, 4
picked = None

print(failing)
print(picked)

None
None

### ✅ Solution

In [ ]:
failing = scores[scores < 50]
picked = scores[[1, 2, 4]]

print(failing)
print(picked)

[47 30]
[82 47 63]

## 1.5 Vectorized arithmetic & broadcasting

In [ ]:
prices = np.array([100, 250, 80, 400])
qty = np.array([2, 1, 5, 1])

print("total per item:", prices * qty)
print("grand total   :", (prices * qty).sum())

# Broadcasting: apply a flat 10% discount to every price
discounted = prices * 0.9
print("discounted    :", discounted)

# Broadcasting a row vector across a matrix
matrix = np.ones((3, 4))
row = np.array([1, 2, 3, 4])
print("broadcast add:\n", matrix + row)

total per item: [200 250 400 400]
grand total   : 1250
discounted    : [ 90. 225.  72. 360.]
broadcast add:
 [[2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]]

### 🧪 Try it
1. Given `celsius = np.array([0, 10, 20, 30, 40])`, convert to Fahrenheit: `F = C * 9/5 + 32`.
2. Given a `(3,3)` matrix of ones, add the column vector `[[10],[20],[30]]` to it using broadcasting.

In [ ]:
celsius = np.array([0, 10, 20, 30, 40])

# TODO 1: convert to Fahrenheit
fahrenheit = None

base = np.ones((3, 3))
col = np.array([[10], [20], [30]])

# TODO 2: broadcast-add col to base
result = None

print(fahrenheit)
print(result)

None
None

### ✅ Solution

In [ ]:
fahrenheit = celsius * 9 / 5 + 32
result = base + col

print(fahrenheit)
print(result)

[ 32.  50.  68.  86. 104.]
[[11. 11. 11.]
 [21. 21. 21.]
 [31. 31. 31.]]

## 1.6 Ufuncs & aggregations

In [ ]:
vals = np.array([[4, 9, 16], [1, 25, 36]])

print("sqrt        :\n", np.sqrt(vals))
print("sum (all)   :", vals.sum())
print("sum (axis=0):", vals.sum(axis=0)) #column wise summation of elements
print("sum (axis=1):", vals.sum(axis=1)) #row wise summation of elements
print("mean        :", vals.mean())
print("max per row :", vals.max(axis=1)) # find out the maximum element in the row

sqrt        :
 [[2. 3. 4.]
 [1. 5. 6.]]
sum (all)   : 91
sum (axis=0): [ 5 34 52]
sum (axis=1): [29 62]
mean        : 15.166666666666666
max per row : [16 36]

### 🧪 Try it
Given `matrix = np.array([[2, 4, 6], [1, 3, 5], [10, 20, 30]])`:
1. Compute the mean of each **column** (axis=0).
2. Compute the row that has the highest sum.

In [ ]:
matrix = np.array([[2, 4, 6], [1, 3, 5], [10, 20, 30]])

# TODO 1: mean per column
col_means = None

# TODO 2: index of the row with the highest sum
row_sums = matrix.sum(axis=1)
best_row_index = None

print(col_means)
print(best_row_index)

None
None

### ✅ Solution

In [ ]:
col_means = matrix.mean(axis=0)
row_sums = matrix.sum(axis=1)
best_row_index = row_sums.argmax() #prints it

print(col_means)
print(best_row_index, "-> row", matrix[best_row_index])

[ 4.33333333  9.         13.66666667]
2 -> row [10 20 30]

## 1.7 Reshaping, transposing & stacking

In [ ]:
nums = np.arange(12)
print("original :", nums)

reshaped = nums.reshape(3, 4)
print("reshaped :\n", reshaped) # change the shape of the matrix
print("transposed:\n", reshaped.T) # find the transpose of the matrix

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print("vstack:\n", np.vstack([a, b]))
print("hstack:\n", np.hstack([a, b]))

original : [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
transposed:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack:
 [[1 2 5 6]
 [3 4 7 8]]

### 🎯 Mini-challenge — NumPy
You track daily step counts for 4 weeks (28 days) in a flat array. Reshape it into a `(4, 7)`
grid (weeks x days), then find the total steps per week and which single day had the most steps overall.

In [ ]:
np.random.seed(42)
daily_steps = np.random.randint(3000, 12000, size=28)

# TODO: reshape into (4 weeks, 7 days)
weekly_grid = None

# TODO: total steps per week (axis that sums across days)
steps_per_week = None

# TODO: index (0-27) of the single best day, and its step count
best_day_index = None
best_day_steps = None

print(weekly_grid)
print("Per-week totals:", steps_per_week)
print("Best day:", best_day_index, "with", best_day_steps, "steps")

None
Per-week totals: None
Best day: None with None steps

### ✅ Solution

In [ ]:
weekly_grid = daily_steps.reshape(4, 7)
steps_per_week = weekly_grid.sum(axis=1)
best_day_index = daily_steps.argmax()
best_day_steps = daily_steps[best_day_index]

print(weekly_grid)
print("Per-week totals:", steps_per_week)
print("Best day:", best_day_index, "with", best_day_steps, "steps")

[[10270  3860  8390  8191  8734  9265  3466]
 [ 7426  8578 11322  4685  3769  9949  5433]
 [ 8311  8051  9420  4184  7555  6385  9396]
 [11666  5558 10849  5047  5747  3189  5734]]
Per-week totals: [52176 51162 53302 47790]
Best day: 21 with 11666 steps


---
# Part 2 — Pandas: DataFrames & Data Manipulation

We'll use a small built-in "employees" dataset (no upload needed) so everyone works with the same data.

## 2.1 Building our sample dataset

In [ ]:
employees = pd.DataFrame({
    "name":       ["Ananya","Rohan","Meera","Karan","Priya","Suresh","Divya",
                    "Arjun","Neha","Vikram","Isha","Farhan","Sonal","Ravi"],
    "department": ["Sales","Engineering","Engineering","Marketing","Sales","Engineering",
                    "Marketing","Sales","Engineering","Marketing","Sales","Engineering",
                    "Marketing","Sales"],
    "age":        [29, 34, 41, 26, 38, np.nan, 31, 45, 27, 33, 29, np.nan, 36, 40],
    "city":       ["Pune","Delhi","Pune","Goa","Delhi","Pune","Goa","Pune","Delhi",
                    "Goa","Pune","Delhi","Goa","Pune"],
    "salary":     [52000, 78000, 91000, 45000, np.nan, 83000, 47000, 61000, 72000,
                    np.nan, 49000, 88000, 46000, 58000],
    "join_year":  [2019, 2016, 2014, 2021, 2018, 2015, 2020, 2017, 2019, 2016,
                    2022, 2013, 2018, 2015],
})

departments = pd.DataFrame({
    "department": ["Sales", "Engineering", "Marketing"],
    "manager":    ["Kabir Shah", "Ritu Menon", "Alok Nair"],
    "budget":     [500000, 900000, 300000],
})

employees

      name   department   age   city   salary  join_year
0   Ananya        Sales  29.0   Pune  52000.0       2019
1    Rohan  Engineering  34.0  Delhi  78000.0       2016
2    Meera  Engineering  41.0   Pune  91000.0       2014
3    Karan    Marketing  26.0    Goa  45000.0       2021
4    Priya        Sales  38.0  Delhi      NaN       2018
5   Suresh  Engineering   NaN   Pune  83000.0       2015
6    Divya    Marketing  31.0    Goa  47000.0       2020
7    Arjun        Sales  45.0   Pune  61000.0       2017
8     Neha  Engineering  27.0  Delhi  72000.0       2019
9   Vikram    Marketing  33.0    Goa      NaN       2016
10    Isha        Sales  29.0   Pune  49000.0       2022
11  Farhan  Engineering   NaN  Delhi  88000.0       2013
12   Sonal    Marketing  36.0    Goa  46000.0       2018
13    Ravi        Sales  40.0   Pune  58000.0       2015

## 2.2 Inspecting the DataFrame

In [ ]:
print(employees.shape)
print(employees.dtypes)
employees.info()

(14, 6)
name           object
department     object
age           float64
city           object
salary        float64
join_year       int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        14 non-null     object
 1   department  14 non-null     object
 2   age         12 non-null     float64
 3   city        14 non-null     object
 4   salary      12 non-null     float64
 5   join_year   14 non-null     int64
dtypes: float64(2), int64(1), object(3)
memory usage: 804.0+ bytes

In [ ]:
employees.describe()

             age        salary    join_year
count  12.000000     12.000000    14.000000
mean   34.083333  64166.666667  2017.357143
std     6.022055  17356.336717     2.677747
min    26.000000  45000.000000  2013.000000
25%    29.000000  48500.000000  2015.250000
50%    33.500000  59500.000000  2017.500000
75%    38.500000  79250.000000  2019.000000
max    45.000000  91000.000000  2022.000000

In [ ]:
employees.head(3)

     name   department   age   city   salary  join_year
0  Ananya        Sales  29.0   Pune  52000.0       2019
1   Rohan  Engineering  34.0  Delhi  78000.0       2016
2   Meera  Engineering  41.0   Pune  91000.0       2014

### 🧪 Try it
1. Show the **last** 4 rows of `employees`.
2. Print the column names.

In [ ]:
# TODO 1: last 4 rows
last_rows = None

# TODO 2: column names
col_names = None

print(last_rows)
print(col_names)

None
None

### ✅ Solution

In [ ]:
last_rows = employees.tail(4)
col_names = employees.columns

print(last_rows)
print(col_names)

      name   department   age   city   salary  join_year
10    Isha        Sales  29.0   Pune  49000.0       2022
11  Farhan  Engineering   NaN  Delhi  88000.0       2013
12   Sonal    Marketing  36.0    Goa  46000.0       2018
13    Ravi        Sales  40.0   Pune  58000.0       2015
Index(['name', 'department', 'age', 'city', 'salary', 'join_year'], dtype='object')

## 2.3 Selecting data: loc vs. iloc

In [ ]:
print(employees["name"].head())          # single column -> Series
print(employees[["name", "department"]].head())  # multiple columns -> DataFrame

print(employees.loc[0, "name"])          # by label
print(employees.iloc[0, 0])              # by position

print(employees.loc[0:2, ["name", "age"]])
print(employees.iloc[0:3, 0:2])

0    Ananya
1     Rohan
2     Meera
3     Karan
4     Priya
Name: name, dtype: object
     name   department
0  Ananya        Sales
1   Rohan  Engineering
2   Meera  Engineering
3   Karan    Marketing
4   Priya        Sales
Ananya
Ananya
     name   age
0  Ananya  29.0
1   Rohan  34.0
2   Meera  41.0
     name   department
0  Ananya        Sales
1   Rohan  Engineering
2   Meera  Engineering

### 🧪 Try it
1. Select just the `city` and `salary` columns for **all rows**.
2. Using `.iloc`, select the first 5 rows and the last 2 columns.

In [ ]:
# TODO 1: city & salary columns
city_salary = None

# TODO 2: first 5 rows, last 2 columns (iloc)
subset = None

print(city_salary)
print(subset)

None
None

### ✅ Solution

In [ ]:
city_salary = employees[["city", "salary"]]
subset = employees.iloc[0:5, -2:]

print(city_salary.head())
print(subset)

    city   salary
0   Pune  52000.0
1  Delhi  78000.0
2   Pune  91000.0
3    Goa  45000.0
4  Delhi      NaN
    salary  join_year
0  52000.0       2019
1  78000.0       2016
2  91000.0       2014
3  45000.0       2021
4      NaN       2018

## 2.4 Filtering with conditions

In [ ]:
print(employees[employees["age"] > 35])

print(employees[(employees["department"] == "Engineering") & (employees["city"] == "Pune")])

print(employees.query("salary > 60000"))

print(employees[employees["city"].isin(["Goa", "Delhi"])])

     name   department   age   city   salary  join_year
2   Meera  Engineering  41.0   Pune  91000.0       2014
4   Priya        Sales  38.0  Delhi      NaN       2018
7   Arjun        Sales  45.0   Pune  61000.0       2017
12  Sonal    Marketing  36.0    Goa  46000.0       2018
13   Ravi        Sales  40.0   Pune  58000.0       2015
     name   department   age  city   salary  join_year
2   Meera  Engineering  41.0  Pune  91000.0       2014
5  Suresh  Engineering   NaN  Pune  83000.0       2015
      name   department   age   city   salary  join_year
1    Rohan  Engineering  34.0  Delhi  78000.0       2016
2    Meera  Engineering  41.0   Pune  91000.0       2014
5   Suresh  Engineering   NaN   Pune  83000.0       2015
7    Arjun        Sales  45.0   Pune  61000.0       2017
8     Neha  Engineering  27.0  Delhi  72000.0       2019
11  Farhan  Engineering   NaN  Delhi  88000.0       2013
      name   department   age   city   salary  join_year
1    Rohan  Engineering  34.0  Delhi  78000.0       2016
3    Karan    Marketing  26.0    Goa  45000.0       2021
4    Priya        Sales  38.0  Delhi      NaN       2018
6    Divya    Marketing  31.0    Goa  47000.0       2020
8     Neha  Engineering  27.0  Delhi  72000.0       2019
9   Vikram    Marketing  33.0    Goa      NaN       2016
11  Farhan  Engineering   NaN  Delhi  88000.0       2013
12   Sonal    Marketing  36.0    Goa  46000.0       2018

### 🧪 Try it
1. Filter employees in the `Sales` department earning more than `50000`.
2. Filter employees who joined in `2019` or later.

In [ ]:
# TODO 1: Sales dept, salary > 50000
sales_high_earners = None

# TODO 2: joined 2019 or later
recent_joiners = None

print(sales_high_earners)
print(recent_joiners)

None
None

### ✅ Solution

In [ ]:
sales_high_earners = employees[(employees["department"] == "Sales") & (employees["salary"] > 50000)]
recent_joiners = employees[employees["join_year"] >= 2019]

print(sales_high_earners)
print(recent_joiners)

      name department   age  city   salary  join_year
0   Ananya      Sales  29.0  Pune  52000.0       2019
7    Arjun      Sales  45.0  Pune  61000.0       2017
13    Ravi      Sales  40.0  Pune  58000.0       2015
      name   department   age   city   salary  join_year
0   Ananya        Sales  29.0   Pune  52000.0       2019
3    Karan    Marketing  26.0    Goa  45000.0       2021
6    Divya    Marketing  31.0    Goa  47000.0       2020
8     Neha  Engineering  27.0  Delhi  72000.0       2019
10    Isha        Sales  29.0   Pune  49000.0       2022

## 2.5 Adding, modifying & dropping columns

In [ ]:
employees["age_next_year"] = employees["age"] + 1
employees["is_senior"] = employees["join_year"] <= 2016
employees["name_upper"] = employees["name"].apply(lambda x: x.upper())

employees.head()

,name,department,age,city,salary,join_year,age_next_year,is_senior,name_upper
0,Ananya,Sales,29.0,Pune,52000.0,2019,30.0,False,ANANYA
1,Rohan,Engineering,34.0,Delhi,78000.0,2016,35.0,True,ROHAN
2,Meera,Engineering,41.0,Pune,91000.0,2014,42.0,True,MEERA
3,Karan,Marketing,26.0,Goa,45000.0,2021,27.0,False,KARAN
4,Priya,Sales,38.0,Delhi,NaN,2018,39.0,False,PRIYA

### 🧪 Try it
1. Add a column `monthly_salary` = `salary / 12`.
2. Drop the `name_upper` column (we don't need it anymore).

In [ ]:
# TODO 1: monthly_salary column
employees["monthly_salary"] = None

# TODO 2: drop name_upper
employees_clean = None

employees_clean

### ✅ Solution

In [ ]:
employees["monthly_salary"] = employees["salary"] / 12
employees_clean = employees.drop(columns=["name_upper"])

employees_clean.head()

,name,department,age,city,salary,join_year,age_next_year,is_senior,monthly_salary
0,Ananya,Sales,29.0,Pune,52000.0,2019,30.0,False,4333.333333
1,Rohan,Engineering,34.0,Delhi,78000.0,2016,35.0,True,6500.000000
2,Meera,Engineering,41.0,Pune,91000.0,2014,42.0,True,7583.333333
3,Karan,Marketing,26.0,Goa,45000.0,2021,27.0,False,3750.000000
4,Priya,Sales,38.0,Delhi,NaN,2018,39.0,False,NaN

## 2.6 Handling missing data
Notice `age` and `salary` have some `NaN` values by design — perfect for practicing this.

In [ ]:
print(employees_clean.isna().sum())

# Drop rows missing salary
no_missing_salary = employees_clean.dropna(subset=["salary"])
print(no_missing_salary.shape)

# Fill missing age with the column mean
filled = employees_clean.copy()
filled["age"] = filled["age"].fillna(filled["age"].mean())
print(filled["age"])

name              0
department        0
age               2
city              0
salary            2
join_year         0
age_next_year     2
is_senior         0
monthly_salary    2
dtype: int64
(12, 9)
0     29.000000
1     34.000000
2     41.000000
3     26.000000
4     38.000000
5     34.083333
6     31.000000
7     45.000000
8     27.000000
9     33.000000
10    29.000000
11    34.083333
12    36.000000
13    40.000000
Name: age, dtype: float64

### 🧪 Try it
1. Count how many `NaN` values are in the `age` column only.
2. Fill missing `salary` values with the **median** salary (not the mean).

In [ ]:
# TODO 1: count NaNs in age
age_nan_count = None

# TODO 2: fill missing salary with median
filled_salary = employees_clean.copy()
filled_salary["salary"] = None

print(age_nan_count)
print(filled_salary["salary"])

None
0     None
1     None
2     None
3     None
4     None
5     None
6     None
7     None
8     None
9     None
10    None
11    None
12    None
13    None
Name: salary, dtype: object

### ✅ Solution

In [ ]:
age_nan_count = employees_clean["age"].isna().sum()

filled_salary = employees_clean.copy()
filled_salary["salary"] = filled_salary["salary"].fillna(filled_salary["salary"].median())

print(age_nan_count)
print(filled_salary["salary"])

2
0     52000.0
1     78000.0
2     91000.0
3     45000.0
4     59500.0
5     83000.0
6     47000.0
7     61000.0
8     72000.0
9     59500.0
10    49000.0
11    88000.0
12    46000.0
13    58000.0
Name: salary, dtype: float64

## 2.7 Sorting values

In [ ]:
print(employees_clean.sort_values("salary", ascending=False).head())

print(employees_clean.sort_values(["department", "age"], ascending=[True, False]).head())

      name   department   age   city   salary  join_year  age_next_year  \
2    Meera  Engineering  41.0   Pune  91000.0       2014           42.0
11  Farhan  Engineering   NaN  Delhi  88000.0       2013            NaN
5   Suresh  Engineering   NaN   Pune  83000.0       2015            NaN
1    Rohan  Engineering  34.0  Delhi  78000.0       2016           35.0
8     Neha  Engineering  27.0  Delhi  72000.0       2019           28.0

    is_senior  monthly_salary
2        True     7583.333333
11       True     7333.333333
5        True     6916.666667
1        True     6500.000000
8       False     6000.000000
      name   department   age   city   salary  join_year  age_next_year  \
2    Meera  Engineering  41.0   Pune  91000.0       2014           42.0
1    Rohan  Engineering  34.0  Delhi  78000.0       2016           35.0
8     Neha  Engineering  27.0  Delhi  72000.0       2019           28.0
5   Suresh  Engineering   NaN   Pune  83000.0       2015            NaN
11  Farhan  Engineering   NaN  Delhi  88000.0       2013            NaN

    is_senior  monthly_salary
2        True     7583.333333
1        True     6500.000000
8       False     6000.000000
5        True     6916.666667
11       True     7333.333333

### 🧪 Try it
Sort `employees_clean` by `age` (ascending), then reset the index so it starts cleanly at 0.

In [ ]:
# TODO: sort by age ascending, then reset index (drop old index)
sorted_by_age = None

sorted_by_age

### ✅ Solution

In [ ]:
sorted_by_age = employees_clean.sort_values("age").reset_index(drop=True)
sorted_by_age.head()

,name,department,age,city,salary,join_year,age_next_year,is_senior,monthly_salary
0,Karan,Marketing,26.0,Goa,45000.0,2021,27.0,False,3750.000000
1,Neha,Engineering,27.0,Delhi,72000.0,2019,28.0,False,6000.000000
2,Ananya,Sales,29.0,Pune,52000.0,2019,30.0,False,4333.333333
3,Isha,Sales,29.0,Pune,49000.0,2022,30.0,False,4083.333333
4,Divya,Marketing,31.0,Goa,47000.0,2020,32.0,False,3916.666667

## 2.8 GroupBy: split — apply — combine

In [ ]:
print(employees_clean.groupby("department")["salary"].mean())

print(employees_clean.groupby("department").agg(
    avg_age=("age", "mean"),
    avg_salary=("salary", "mean"),
    headcount=("name", "size"),
))

department
Engineering    82400.0
Marketing      46000.0
Sales          55000.0
Name: salary, dtype: float64
             avg_age  avg_salary  headcount
department
Engineering     34.0     82400.0          5
Marketing       31.5     46000.0          4
Sales           36.2     55000.0          5

### 🧪 Try it
1. Find the average `age` per `city`.
2. Find the max `salary` per `department`.

In [ ]:
# TODO 1: average age per city
avg_age_by_city = None

# TODO 2: max salary per department
max_salary_by_dept = None

print(avg_age_by_city)
print(max_salary_by_dept)

None
None

### ✅ Solution

In [ ]:
avg_age_by_city = employees_clean.groupby("city")["age"].mean()
max_salary_by_dept = employees_clean.groupby("department")["salary"].max()

print(avg_age_by_city)
print(max_salary_by_dept)

city
Delhi    33.0
Goa      31.5
Pune     36.8
Name: age, dtype: float64
department
Engineering    91000.0
Marketing      47000.0
Sales          61000.0
Name: salary, dtype: float64

## 2.9 Merging & concatenating DataFrames

In [ ]:
merged = pd.merge(employees_clean, departments, on="department", how="left")
merged[["name", "department", "manager", "budget"]].head()

     name   department     manager  budget
0  Ananya        Sales  Kabir Shah  500000
1   Rohan  Engineering  Ritu Menon  900000
2   Meera  Engineering  Ritu Menon  900000
3   Karan    Marketing   Alok Nair  300000
4   Priya        Sales  Kabir Shah  500000

In [ ]:
# Concatenating: imagine two new-hire batches arriving separately
batch_a = pd.DataFrame({"name": ["Tanvi", "Om"], "department": ["Sales", "Marketing"]})
batch_b = pd.DataFrame({"name": ["Zara"], "department": ["Engineering"]})

new_hires = pd.concat([batch_a, batch_b], ignore_index=True)
new_hires

    name   department
0  Tanvi        Sales
1     Om    Marketing
2   Zara  Engineering

### 🧪 Try it
1. Merge `employees_clean` with `departments` using an **inner** join, keeping only the
   `name`, `department`, and `manager` columns.

In [ ]:
# TODO: inner merge, then select name/department/manager
inner_merged = None

inner_merged

### ✅ Solution

In [ ]:
inner_merged = pd.merge(employees_clean, departments, on="department", how="inner")[
    ["name", "department", "manager"]
]

inner_merged.head()

     name   department     manager
0  Ananya        Sales  Kabir Shah
1   Rohan  Engineering  Ritu Menon
2   Meera  Engineering  Ritu Menon
3   Karan    Marketing   Alok Nair
4   Priya        Sales  Kabir Shah

## 2.10 apply(), map() & lambda functions

In [ ]:
city_codes = {"Pune": "PN", "Delhi": "DL", "Goa": "GA"}
employees_clean["city_code"] = employees_clean["city"].map(city_codes)

employees_clean["age_group"] = employees_clean["age"].apply(
    lambda x: "unknown" if pd.isna(x) else ("senior" if x >= 35 else "junior")
)

employees_clean[["name", "city", "city_code", "age", "age_group"]].head(6)

     name   city city_code   age age_group
0  Ananya   Pune        PN  29.0    junior
1   Rohan  Delhi        DL  34.0    junior
2   Meera   Pune        PN  41.0    senior
3   Karan    Goa        GA  26.0    junior
4   Priya  Delhi        DL  38.0    senior
5  Suresh   Pune        PN   NaN   unknown

### 🧪 Try it
Create a `salary_band` column: `"high"` if salary > 70000, `"mid"` if between 50000-70000
(inclusive), otherwise `"low"`. Missing salaries should map to `"unknown"`.

In [ ]:
def salary_band(s):
    # TODO: implement the logic described above
    pass

employees_clean["salary_band"] = employees_clean["salary"].apply(salary_band)
employees_clean[["name", "salary", "salary_band"]]

      name   salary salary_band
0   Ananya  52000.0        None
1    Rohan  78000.0        None
2    Meera  91000.0        None
3    Karan  45000.0        None
4    Priya      NaN        None
5   Suresh  83000.0        None
6    Divya  47000.0        None
7    Arjun  61000.0        None
8     Neha  72000.0        None
9   Vikram      NaN        None
10    Isha  49000.0        None
11  Farhan  88000.0        None
12   Sonal  46000.0        None
13    Ravi  58000.0        None

### ✅ Solution

In [ ]:
def salary_band(s):
    if pd.isna(s):
        return "unknown"
    elif s > 70000:
        return "high"
    elif s >= 50000:
        return "mid"
    else:
        return "low"

employees_clean["salary_band"] = employees_clean["salary"].apply(salary_band)
employees_clean[["name", "salary", "salary_band"]]

      name   salary salary_band
0   Ananya  52000.0         mid
1    Rohan  78000.0        high
2    Meera  91000.0        high
3    Karan  45000.0         low
4    Priya      NaN     unknown
5   Suresh  83000.0        high
6    Divya  47000.0         low
7    Arjun  61000.0         mid
8     Neha  72000.0        high
9   Vikram      NaN     unknown
10    Isha  49000.0         low
11  Farhan  88000.0        high
12   Sonal  46000.0         low
13    Ravi  58000.0         mid

## 🎯 Mini-challenge — Pandas capstone
Using `employees_clean`, in a single chain (or a few steps):
1. Fill missing `salary` with the department's mean salary (not the overall mean).
2. Group by `department` and compute the average `salary` and headcount.
3. Sort the result by average salary, descending.

In [ ]:
# TODO: fill missing salary with each row's DEPARTMENT mean, then group + sort
df = employees_clean.copy()

df["salary"] = None  # hint: groupby("department")["salary"].transform("mean")

summary = None  # groupby department -> avg_salary, headcount
summary_sorted = None  # sort by avg_salary descending

summary_sorted

### ✅ Solution

In [ ]:
df = employees_clean.copy()
df["salary"] = df["salary"].fillna(df.groupby("department")["salary"].transform("mean"))

summary = df.groupby("department").agg(
    avg_salary=("salary", "mean"),
    headcount=("name", "size"),
)
summary_sorted = summary.sort_values("avg_salary", ascending=False)

summary_sorted

             avg_salary  headcount
department
Engineering     82400.0          5
Sales           55000.0          5
Marketing       46000.0          4

---
## Wrap-up

You've now practiced:
- Creating, indexing, and reshaping NumPy arrays
- Vectorized operations, broadcasting, ufuncs, and aggregations
- Building, inspecting, filtering, and cleaning Pandas DataFrames
- GroupBy, merging, concatenating, and custom row-wise logic with `apply`/`map`

**Next steps:** try re-running the mini-challenges on a dataset of your own (e.g. a CSV export
from work), and revisit the slide deck for a quick reference on syntax.